set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
get_filename_component(POKETCG_WINDOWS_TOOLS "${CMAKE_CURRENT_LIST_DIR}/../../build/windows/tools" ABSOLUTE)
set(CMAKE_C_COMPILER "${POKETCG_WINDOWS_TOOLS}/mingw/usr/bin/x86_64-w64-mingw32-gcc-posix")
set(CMAKE_RC_COMPILER "${POKETCG_WINDOWS_TOOLS}/mingw/usr/bin/x86_64-w64-mingw32-windres")
set(CMAKE_FIND_ROOT_PATH
	"${POKETCG_WINDOWS_TOOLS}/mingw/usr/x86_64-w64-mingw32"
	"${POKETCG_WINDOWS_TOOLS}/SDL2-2.32.10/x86_64-w64-mingw32")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_C_FLAGS_INIT "-DSDL_MAIN_HANDLED -isystem ${POKETCG_WINDOWS_TOOLS}/SDL2-2.32.10/x86_64-w64-mingw32/include")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static -mwindows -Wl,--export-all-symbols")
