"""The routines this slice ports, grouped by their pret source file.

`oracle-diff-all` walks this list, so a routine here with no CASES entry is a
FAIL rather than a silent pass. Dead code (zero callsites in poketcg/src) and
trampolines that become direct C calls at their callsites are deliberately absent.
"""

ROUTINES: dict[str, tuple[str, ...]] = {
    "copy": ("CopyGfxData", "CopyDataHLtoDE_SaveRegisters", "CopyDataHLtoDE"),
    "math": ("ATimes10",),
    "division": ("DivideBCbyDE",),
    "list": ("SetListPointer", "SetNextElementOfList"),
    "memory": ("DecompressDataFromBank", "CopyBankedDataToDE", "FillMemoryWithA",
               "FillMemoryWithDE", "GetFarByte"),
    "random": ("HtimesL", "Random", "UpdateRNGSources"),
    "decompress": ("InitDataDecompression", "DecompressData", "DecompressData.Decompress"),
    "write_number": ("TwoByteNumberToText", "WriteOneByteNumber",
                     "WriteTwoByteNumber", "WriteBCDDigitInTextFormat"),
    "clear_saved_duel": ("ClearSavedDuel",),
    "bg_map": ("WriteDataBlocksToBGMap0", "WriteDataBlockToBGMap0", "WriteByteToBGMap0",
               "HblankWriteByteToBGMap0", "CopyDataToBGMap0", "SafeCopyDataHLtoDE",
               "JPHblankCopyDataHLtoDE"),
    "empty_screen": ("EmptyScreen", "BCCoordToBGMap0Address"),
    "tiles": ("FillRectangle", "Copy1bppTiles", "CopyFontsOrDuelGraphicsTiles",
              "LoadSymbolsFont", "LoadCardSet2Tiles", "LoadDuelDrawCardsScreenTiles",
              "LoadCardOrDuelMenuBorderTiles", "LoadCardTypeHeaderTiles",
              "LoadDuelCardSymbolTiles", "LoadDuelCardSymbolTiles2",
              "LoadDuelFaceDownCardTiles", "LoadDuelCheckPokemonScreenTiles",
              "LoadPlacingThePrizesScreenTiles", "LoadDeckAndDiscardPileIcons",
              "LoadDuelCoinTossResultTiles", "Func_212f", "DrawDuelBoxMessage",
              "LoadFullWidthFontTiles"),
    "text_box": ("SafeCopyDataDEtoHL", "DECoordToBGMap0Address",
                 "AdjustCoordinatesForBGScroll", "CopyLine", "DrawRegularTextBox",
                 "DrawRegularTextBoxDMG", "ContinueDrawingTextBoxDMGorSGB",
                 "DrawRegularTextBoxCGB", "ContinueDrawingTextBoxCGB",
                 "CopyCurrentLineTilesAndAttrCGB", "CopyCurrentLineAttrCGB",
                 "DrawLabeledTextBox"),
    "duel": ("CopyPlayerName", "CopyOpponentName",
             "GetTurnDuelistVariable", "GetNonTurnDuelistVariable", "SwapTurn",
             "_GetCardIDFromDeckIndex", "GetCardIDFromDeckIndex",
             "GetCardIDFromDeckIndex_bc", "GetCardInDuelTempList_OnlyDeckIndex",
             "GetCardInDuelTempList",
             "LoadCardDataToBuffer1_FromDeckIndex", "LoadCardDataToBuffer2_FromDeckIndex",
             "SubtractHP", "CreateDeckCardList", "CreateDiscardPileCardList",
             "RemoveCardFromDuelTempList", "CountCardsInDuelTempList",
             "FindLastCardInHand", "CreateHandCardList",
             "CreateArenaOrBenchEnergyCardList", "ShuffleCards",
             "SortCardsInListByID", "SortCardsInDuelTempListByID",
             "SortHandCardsByID", "TranslateColorToWR",
             "CountCardIDInLocation", "CheckLoadedAttackFlag",
             "GetCardDamageAndMaxHP",
             "CopyDeckData", "CountPrizes", "ShuffleDeck", "DrawCardFromDeck",
             "ReturnCardToDeck", "SearchCardInDeckAndAddToHand", "AddCardToHand",
             "RemoveCardFromHand", "MoveHandCardToDiscardPile", "PutCardInDiscardPile",
             "MoveDiscardPileCardToHand", "CheckPrizeTaken",
             "SortCardsInListByID_CheckForListTerminator",
             "CheckIfCanEvolveInto", "CheckIfCanEvolveInto_BasicToStage2",
             "EvolvePokemonCardIfPossible", "EvolvePokemonCard",
             "ClearAllStatusConditions", "PutHandCardInPlayArea",
             "PutHandPokemonCardInPlayArea", "EmptyPlayAreaSlot",
             "MovePlayAreaCardToDiscardPile", "SwapPlayAreaPokemon",
             "ShiftTurnPokemonToFirstPlayAreaSlots", "ShiftAllPokemonToFirstPlayAreaSlots",
             "SwapArenaWithBenchPokemon", "GetPlayAreaCardAttachedEnergies",
             "CopyAttackDataAndDamage", "CopyAttackDataAndDamage_FromDeckIndex",
             "CopyAttackDataAndDamage_FromCardID", "ReturnCarry",
             "LoadNonPokemonCardEffectCommands", "ApplyAttachedPlusPower",
             "ApplyAttachedDefender", "MoveCardToDiscardPileIfInPlayArea",
             "GetPlayAreaCardRetreatCost",
             "DrawWideTextBox_WaitForInput_ReturnCarry",
             "PrintKnockedOut", "PrintPlayAreaCardKnockedOutIfNoHP"),
    "damage_calculation": ("CalculateDamage_FromDefendingPokemon",
                           "CalculateDamage_VersusDefendingPokemon"),
    "process_text": ("InitTextFormat", "CaseHalfWidthLetter", "ClassifyTextCharacterPair",
                     "GetTextLengthInHalfTiles", "GetTextLengthInTiles",
                     "GetFullWidthFontTileOffset", "ConvertTileNumberToTileDataAddress",
                     "CopyHalfWidthCharacterToDE", "CreateHalfWidthFontTile",
                     "CreateFullWidthFontTile", "CreateFullWidthFontTile_ConvertToTileDataAddress",
                     "GenerateTextTile", "TwoByteNumberToTxSymbol_PadSpace",
                     "ProcessText", "InitTextPrinting_ProcessText", "SetupText",
                     "InitTextPrinting", "InitTextPrintingInTextbox", "PlaceNextTextTile",
                     "ProcessSpecialTextCharacter", "TerminateHalfWidthText",
                     "Func_22ca", "Func_235e", "Func_2325", "CopyTextData"),
    "input": ("ReadJoypad", "SaveButtonsHeld", "ClearJoypad"),
    "labels": ("PrintLabels",),
    "menus": ("InitializeCardListParameters", "InitializeMenuParameters", "SetMenuItem",
              "OneByteNumberToTxSymbol", "OneByteNumberToTxSymbol_PadSpace",
              "OneByteNumberToTxSymbol_TrimLeadingZeroAndAlign", "CardTypeToSymbolID",
              "GetCardSymbolData", "SetCursorParametersForTextBox",
              "SetCursorParametersForTextBox_Default", "DrawCursor", "EraseCursor",
              "DrawCursor2", "RefreshMenuCursor", "DrawCardSymbol", "DrawNarrowTextBox",
              "DrawWideTextBox", "DrawNarrowTextBox_PrintTextNoDelay",
              "DrawWideTextBox_PrintTextNoDelay", "DrawWideTextBox_PrintText",
              "PrintYesOrNoItems", "WaitForButtonAorB",
              "DrawWideTextBox_PrintTextNoDelay_Wait",
              "DrawNarrowTextBox_WaitForInput",
              "DrawWideTextBox_WaitForInput",
              "WaitForWideTextBoxInput"),
    "print_text": ("GetTextOffsetFromTextID", "GetPointerToTextHeader", "ReadTextHeader",
                   "WriteToTextHeader", "WriteToTextHeader_MoveToNext",
                   "ResetTxRam_WriteToTextHeader", "TwoByteNumberToText_CountLeadingZeros",
                   "CopyText", "CountLinesOfTextFromID", "LoadTxRam2", "LoadTxRam3",
                   "ProcessTextHeader", "HandleTxRam2Or3", "CopyTextData_FromTextID",
                   "CopyPlayerNameOrTurnDuelistName", "InitTextPrinting_ProcessTextFromID",
                   "InitTextPrinting_ProcessTextFromPointerToID", "ProcessTextFromID",
                   "ProcessTextFromPointerToID",
                   "PlaceTextItems", "PrintText", "PrintTextNoDelay",
                   "DrawTextReadyLabeledOrRegularTextBox",
                   "WaitForPlayerToAdvanceText", "PrintScrollableText",
                   "PrintScrollableText_NoTextBoxLabel",
                   "PrintScrollableText_WithTextBoxLabel_NoWait",
                   "PrintScrollableText_WithTextBoxLabel"),
    "frames": ("DoAFrames", "DoFrame", "HandleDPadRepeat"),
    "lcd": ("EnableLCD", "DisableLCD", "Set_OBJ_8x8", "Set_OBJ_8x16", "SetWindowOn",
            "SetWindowOff"),
    "card_collection": ("CreateTempCardCollection", "AddCardToCollection",
                        "GetCardAlbumProgress", "GetAmountOfCardsOwned",
                        "GetCardCountInCollectionAndDecks", "GetCardCountInCollection",
                        "RemoveCardFromCollection"),
    "save": ("CopyGeneralSaveDataToSRAM", "ValidateGeneralSaveDataFromDE",
             "LoadGeneralSaveDataFromDE", "WriteDataToBackup", "LoadDataFromBackup",
             "WriteBackupGeneralSaveData", "WriteBackupCardAndDeckSaveData",
             "LoadBackupGeneralSaveData", "LoadBackupCardAndDeckSaveData",
             "InvalidateSaveData", "UpdateAlbumProgress", "LoadAlbumProgressFromSRAM",
             "LoadBackupSaveData", "_LoadGeneralSaveData",
             "_AddCardToCollectionAndUpdateAlbumProgress",
             "ValidateBackupGeneralSaveData", "_ValidateGeneralSaveData",
             "SaveGeneralSaveDataFromDE", "_SaveGeneralSaveData",
             "SaveAndBackupData", "_SaveGame", "SaveGeneralSaveData",
             "LoadGeneralSaveData", "ValidateGeneralSaveData",
             "AddCardToCollectionAndUpdateAlbumProgress", "SaveGame"),
    "dma": ("DMA",),
    "unsafe_bg_map": ("UnsafeWriteDataBlockToBGMap0",),
    "sram": ("BankswitchSRAM",),
    "switch_rom": ("BankswitchROM",),
    "lcd_enable_frame": ("DoFrameIfLCDEnabled",),
    "wait_keys": ("WaitUntilKeysArePressed",),
    "palettes": ("FlushAllPalettes", "FlushPalette", "SetBGP", "FlushPalette0",
                  "FlushPalettes", "SetOBP0", "SetOBP1", "FlushPalettesIfRequested",
                  "CopyCGBPalettes", "FlushAllCGBPalettes"),
    "setup": ("NoOp", "DetectConsole", "SetupPalettes", "FillTileMap",
              "SetupVRAM", "SetupRegisters", "ZeroRAM"),
    "scroll": ("Func_3e44", "GetNextBackgroundScroll", "EnableInt_LYCoincidence",
               "DisableInt_LYCoincidence", "ApplyBackgroundScroll"),
    "load_animation": ("GetFirstSpriteAnimBufferProperty", "GetSpriteAnimBufferProperty",
                        "GetSpriteAnimBufferProperty_SpriteInA", "Func_3ddb", "Func_3de7",
                        "DrawSpriteAnimationFrame", "GetAnimationFramePointer"),
    "animation": ("GetOWFramesetSubgroupData", "LoadOWFramesetSubgroup", "StoreOWFramesetSubgroup", "ClearOWFramesetSubgroups", "ClearNumLoadedFramesetSubgroups"),
    "play_animation": ("CheckAnyAnimationPlaying", "SetDoFrameFunction", "ResetDoFrameFunction"),
    "play_song": ("ScriptPlaySong", "Func_3c87", "WaitForSongToFinish"),
    "duel_animation_core": ("_ResetAnimationQueue", "PlayLoadedDuelAnimation",
                            "LoadDuelAnimationToBuffer", "_UpdateQueuedAnimations",
                            "ClearAndDisableQueuedAnimations"),
    "damage": ("AddToDamage", "SubtractFromDamage"),
    "objects": ("SetOneObjectAttributes", "ZeroObjectPositions", "SetManyObjectsAttributes"),
    "time": ("IncrementPlayTimeCounter", "CheckForCGB", "SetupTimer"),
    "coin_toss": ("CompareDEtoBC",),
    "clear_sram": ("ClearSRAMBank", "RestartSRAM"),
    "card_data": ("GetCardType", "GetCardName", "GetCardTypeRarityAndSet",
                  "LoadCardDataToBuffer1_FromCardID", "LoadCardDataToBuffer2_FromCardID",
                  "LoadCardDataToBuffer1_FromName", "LoadCardGfx", "GetCardPointer"),
    "map": ("GetPermissionByteOfMapPosition", "GetPermissionOfMapPosition",
             "SetPermissionOfMapPosition", "UpdatePermissionOfMapPosition",
             "GetLoadedNPCID", "GetItemInLoadedNPCIndex", "GameEvent_Overworld",
             "CopyGfxDataFromTempBank", "FindLoadedNPC", "GetNextNPCMovementByte",
             "GetDefaultSong"),
    "load_deck": ("LoadDeck",),
    "hall_of_honor": ("HallOfHonorLoadMap",),
    "challenge_hall_lobby": ("Preload_ChallengeHallNPCs2",),
    "ir_functions": ("PlayCardPopSong",),
"card_color": ("GetCardWeakness", "GetArenaCardWeakness", "GetPlayAreaCardWeakness",
               "GetCardResistance", "GetArenaCardResistance", "GetPlayAreaCardResistance",
               "GetArenaCardColor", "GetPlayAreaCardColor", "HandleEnergyBurn"),
    "serial": ("SerialTimerHandler", "Func_0cc5", "SerialHandler",
               "SerialHandleRecv", "SerialHandleSend", "SerialSendByte",
               "Func_0e32", "SerialRecvByte", "SerialExchangeBytes",
               "Func_0e8e", "ResetSerial", "ClearSerialData",
               "SerialSendBytes", "SerialRecvBytes"),
    "printer": ("SendNextPrinterPacketByte", "SendByteThroughSerialData",
                "ExecutePrinterPacketSequence"),
    "duel_core": ("ConvertSpecialTrainerCardToPokemon",
                  "ResetAttackAnimationIsPlaying",
                  "ClearNonTurnTemporaryDuelvars",
                  "ClearNonTurnTemporaryDuelvars_CopyStatus",
                  "UpdateArenaCardLastTurnDamage",
                  "PrintThereWasNoEffectFromStatusText",
                  "WaitAttackAnimation",
                  "ApplyStatusConditionQueue",
                  "GetCardOneStageBelow",
                  "SetDefaultConsolePalettes"),
    "duel_core_state": ("InitVariablesToBeginTurn",
                        "SetAllPlayAreaPokemonCanEvolve",
                        "InitializeDuelVariables",
                        "InitTurnDuelistPrizes",
                        "TakeAPrizes",
                        "CheckIfTurnDuelistPlayAreaPokemonAreAllKnockedOut",
                        "CountKnockedOutPokemon"),
    "default_palettes": ("Func_12871", "SetDefaultPalettes"),
    "load_gfx": ("LoadTilemap_ToSRAM", "LoadTilemap_ToVRAM", "LoadTilemap",
                 "LoadTilemap.InitAndDecompressBGMap", "LoadTilemap.Decompress",
                 "Func_80148", "CopyBGDataToVRAMOrSRAM",
                 "SafelyCopyBGMapFromSRAMToVRAM", "ClearSRAMBGMaps",
                 "GetMapDataPointer", "LoadGraphicsPointerFromHL", "LoadSpriteGfx",
                 "LoadGfxDataFromTempPointerToVRAMBank",
                 "LoadGfxDataFromTempPointerToVRAMBank_Tiles0ToTiles2",
                 "LoadGfxDataFromTempPointer", "GetTileOffsetPointerAndSwitchVRAM",
                 "GetTileOffsetPointerAndSwitchVRAM_Tiles0ToTiles2", "LoadTilesetGfx",
                 "LoadTilesetGfx.LoadTileGfx", "LoadTilesetGfx.CopyGfxData",
                 "Func_803b9", "LoadBGPalette", "LoadPaletteDataFromHL",
                 "LoadOBPalette", "LoadPaletteDataToBuffer"),
    "substatus": ("CheckSandAttackOrSmokescreenSubstatus",
               "CountTurnDuelistPokemonWithActivePkmnPower",
               "CountPokemonWithActivePkmnPowerInBothPlayAreas",
               "CheckIsIncapableOfUsingPkmnPower",
               "CheckIsIncapableOfUsingPkmnPower_ArenaCard",
               "HandleDoubleDamageSubstatus",
               "HandleDamageReductionExceptSubstatus2",
               "HandleDamageReduction",
               "HandleCantAttackSubstatus",
               "HandleAmnesiaSubstatus",
               "HandleNoDamageOrEffectSubstatus",
               "CheckNoDamageOrEffect",
               "IsClairvoyanceActive",
               "GetLoadedCard1RetreatCost",
               "CheckUnableToRetreatDueToEffect",
               "CheckCantUseTrainerDueToEffect",
               "IsPrehistoricPowerActive",
               "ClearDamageReductionSubstatus2",
               "UpdateSubstatusConditions_StartOfTurn",
               "UpdateSubstatusConditions_EndOfTurn",
               "IsRainDanceActive",
               "CheckRainDanceScenario",
               "ClearChangedTypesIfMuk",
               "HandleStrikesBack_AgainstDamagingAttack"),
    "script": ("GetMapScriptPointer",),
    "effect_commands": ("CheckMatchingCommand",),
    "ai": ("LoadOpponentDeck",),
    "music1": ("Music1_EmptyFunc", "Music1_f404e", "Music1_f4066", "Music1_f406f",
               "Music1_PlaySong", "Music1_PlaySFX", "Music1_AssertSongFinished",
               "Music1_AssertSFXFinished", "Music1_CheckForEndOfSong",
               "Music1_Init", "Music1_StopAllChannels", "Music1_f4980",
               "Music1_CopyData", "Music1_BeginSong",
               "Music1_GetChannelStackPointer", "Music1_SetChannelStackPointer",
               "Music1_f4714", "Music1_f475a", "Music1_f479c",
               "Music1_f480a", "Music1_f4839", "Music1_LoadWaveInstrument",
               "Music1_UpdateVibrato", "Music1_f490b", "Music1_f4967",
               "Music1_f485a", "Music1_f4866",
               "Music1_UpdateChannel1", "Music1_UpdateChannel2",
               "Music1_UpdateChannel3", "Music1_UpdateChannel4",
               "Music1_PauseSong", "Music1_ResumeSong",
               "Music1_BackupSong", "Music1_LoadBackup",
               "Music1_CheckForNewSound", "Music1_Update"),
    "music2": ("Music2_EmptyFunc", "Music2_f404e", "Music2_f4066", "Music2_f406f",
               "Music2_PlaySong", "Music2_PlaySFX", "Music2_AssertSongFinished",
               "Music2_AssertSFXFinished", "Music2_CheckForEndOfSong",
               "Music2_Init", "Music2_StopAllChannels", "Music2_f4980",
               "Music2_CopyData", "Music2_BeginSong",
               "Music2_GetChannelStackPointer", "Music2_SetChannelStackPointer",
               "Music2_f4714", "Music2_f475a", "Music2_f479c",
               "Music2_f480a", "Music2_f4839", "Music2_LoadWaveInstrument",
               "Music2_UpdateVibrato", "Music2_f490b", "Music2_f4967",
               "Music2_f485a", "Music2_f4866",
               "Music2_UpdateChannel1", "Music2_UpdateChannel2",
               "Music2_UpdateChannel3", "Music2_UpdateChannel4",
               "Music2_PauseSong", "Music2_ResumeSong",
               "Music2_BackupSong", "Music2_LoadBackup",
               "Music2_CheckForNewSound", "Music2_Update"),
    "sfx": ("SFX_PlaySFX", "SFX_UpdateSFX"),
    "sound": ("Func_37c5", "Func_37a5",
              "SetupSound", "StopMusic", "PlaySong",
              "AssertSongFinished", "AssertSFXFinished",
              "PlaySFX_InvalidChoice", "PlaySFX",
              "PauseSong", "ResumeSong"),
    "init_menu": ("InitMenuScreen", "FlashWhiteScreen"),
    "color": ("LoadConsolePaletteData", "FadeScreenToWhite",
              "FadeScreenFromWhite.BackupPalsAndSetWhite", "SetWhitePalettes",
              "Func_10d17", "Func_10d50", "FadeScreenFromWhite",
              "FadeScreenToTempPals", "RestoreFirstColorInOBPals",
              "FadeDMGPalettes", "FadeDMGPalettes.CalculateMixPalette",
              "FadeDMGPalettes.GetMixShadeValue", "FadeOBPalIntoTemp",
              "FadeBGPalIntoTemp1", "FadeBGPalIntoTemp2", "FadeBGPalIntoTemp3",
              "FadePalIntoAnother.GetFadedColor", "FadePalIntoAnother.FadeColor",
              "FlashScreenToWhite", "CopyPalsToSRAMBuffer", "LoadPalsFromSRAMBuffer",
              "Func_10d74"),
    "sprite_animations": ("_ClearSpriteAnimations",
                          "CreateSpriteAndAnimBufferEntry",
                          "FillNewSpriteAnimBufferEntry",
                          "DisableCurSpriteAnim", "DisableSpriteAnim",
                          "GetSpriteAnimCounter", "_HandleAllSpriteAnimations",
                          "LoadSpriteDataForAnimationFrame",
                          "TryHandleSpriteAnimationFrame",
                          "StartNewSpriteAnimation", "StartSpriteAnimation",
                          "Func_12ac9", "LoadSpriteAnimPointers",
                          "HandleAnimationFrame", "GetAnimFramePointerFromOffset",
                          "SetAnimationCounterAndLoop", "Func_12ba7", "Func_12bcd",
                          "ClearSpriteVRAMBuffer", "Func_12c05", "Func_12c4f",
                          "Func_12c5e"),
    "duel_core_status": ("IsArenaPokemonAsleepOrPoisoned",
                         "DiscardAttachedPlusPowers", "DiscardAttachedDefenders"),
    "debug_main": ("Func_126b3",),
    "give_booster_pack": ("_PauseMenu_Exit",),
    "debug_sprites": ("Func_1c890", "Func_1c866", "Func_1c865"),
    "card_pop": ("CreateCardPopCandidateList", "CalculateNameHash"),
    "credits_sequence_commands": ("SetCreditsSequenceCmdPtr", "ExecuteCreditsSequenceCmd",
                                  "AdvanceCreditsSequenceCmdPtr"),
    "debug_player_coordinates": ("JumpSetWindowOff",),
    "deck_machine_room": ("Func_d96c", "Script_BeatAaron"),
    "warp": ("_HandleMapWarp",),
}

EXCLUSIONS: dict[str, dict[str, dict[str, str]]] = {
    "write_number": {
        "WriteBCDDigitInTextFormat": {
            "kind": "dead-zero-callsites",
            "source": "poketcg/src/home/write_number.asm:78-86",
            "reason": "definition plus dead-family internal calls; zero live callsites in poketcg/src",
        },
        "WriteOneByteNumber": {
            "kind": "dead-zero-callsites",
            "source": "poketcg/src/home/write_number.asm:90-111",
            "reason": "definition only; zero callsites in poketcg/src",
        },
        "WriteTwoByteNumber": {
            "kind": "dead-zero-callsites",
            "source": "poketcg/src/home/write_number.asm:115-125",
            "reason": "definition only; zero callsites in poketcg/src",
        },
    },
    "deck_machine_room": {
        "Script_BeatAaron": {
            "kind": "hardware-transform",
            "source": "poketcg/src/scripts/deck_machine_room.asm:62-76",
            "reason": "script engine commands start_script, print_npc_text, give_booster_packs, and script_jump expand into unported engine dependencies",
        },
    },
}

ALL = tuple(fn for group in ROUTINES.values() for fn in group)
