"""The routines this slice ports, grouped by their pret source file.

`oracle-diff-all` walks this list, so a routine here with no CASES entry is a
FAIL rather than a silent pass. Dead code (zero callsites in poketcg/src) and
trampolines that become direct C calls at their callsites are deliberately absent.
"""

ROUTINES: dict[str, tuple[str, ...]] = {
    "copy": ("CopyGfxData", "CopyDataHLtoDE_SaveRegisters", "CopyDataHLtoDE"),
    "math": ("ATimes10",),
    "division": ("DivideBCbyDE",),
    "list": ("SetListPointer", "SetNextElementOfList"),
    "memory": ("DecompressDataFromBank", "CopyBankedDataToDE", "FillMemoryWithA",
               "FillMemoryWithDE", "GetFarByte"),
    "random": ("HtimesL", "Random", "UpdateRNGSources"),
    "decompress": ("InitDataDecompression", "DecompressData", "DecompressData.Decompress"),
    "write_number": ("TwoByteNumberToText",),
    "clear_sram_bg_maps": ("ClearSRAMBGMaps",),
    "clear_saved_duel": ("ClearSavedDuel",),
    "bg_map": ("WriteDataBlocksToBGMap0", "WriteDataBlockToBGMap0", "WriteByteToBGMap0",
               "HblankWriteByteToBGMap0", "CopyDataToBGMap0", "SafeCopyDataHLtoDE",
               "JPHblankCopyDataHLtoDE"),
    "empty_screen": ("EmptyScreen", "BCCoordToBGMap0Address"),
    "tiles": ("FillRectangle", "Copy1bppTiles"),
    "text_box": ("SafeCopyDataDEtoHL", "DECoordToBGMap0Address",
                 "AdjustCoordinatesForBGScroll", "CopyLine", "DrawRegularTextBox",
                 "DrawRegularTextBoxDMG", "ContinueDrawingTextBoxDMGorSGB",
                 "DrawRegularTextBoxCGB", "ContinueDrawingTextBoxCGB",
                 "CopyCurrentLineTilesAndAttrCGB", "CopyCurrentLineAttrCGB",
                 "DrawLabeledTextBox"),
    "duel": ("CopyPlayerName", "CopyOpponentName"),
    "process_text": ("InitTextFormat", "CaseHalfWidthLetter", "ClassifyTextCharacterPair",
                     "GetTextLengthInHalfTiles", "GetTextLengthInTiles",
                     "GetFullWidthFontTileOffset", "ConvertTileNumberToTileDataAddress",
                     "CopyHalfWidthCharacterToDE", "CreateHalfWidthFontTile",
                     "CreateFullWidthFontTile", "CreateFullWidthFontTile_ConvertToTileDataAddress",
                     "GenerateTextTile", "TwoByteNumberToTxSymbol_PadSpace",
                     "ProcessText", "InitTextPrinting_ProcessText", "SetupText",
                     "InitTextPrinting", "InitTextPrintingInTextbox", "PlaceNextTextTile",
                     "ProcessSpecialTextCharacter", "TerminateHalfWidthText",
                     "Func_22ca", "Func_235e", "Func_2325", "CopyTextData"),
    "input": ("ReadJoypad", "SaveButtonsHeld", "ClearJoypad"),
    "menus": ("InitializeCardListParameters", "InitializeMenuParameters", "SetMenuItem",
              "OneByteNumberToTxSymbol", "OneByteNumberToTxSymbol_PadSpace",
              "OneByteNumberToTxSymbol_TrimLeadingZeroAndAlign", "CardTypeToSymbolID",
              "GetCardSymbolData"),
    "print_text": ("GetTextOffsetFromTextID", "GetPointerToTextHeader", "ReadTextHeader",
                   "WriteToTextHeader", "WriteToTextHeader_MoveToNext",
                   "ResetTxRam_WriteToTextHeader", "TwoByteNumberToText_CountLeadingZeros",
                   "CopyText", "CountLinesOfTextFromID", "LoadTxRam2", "LoadTxRam3",
                   "ProcessTextHeader", "HandleTxRam2Or3", "CopyTextData_FromTextID",
                   "CopyPlayerNameOrTurnDuelistName", "InitTextPrinting_ProcessTextFromID",
                   "InitTextPrinting_ProcessTextFromPointerToID", "ProcessTextFromID",
                   "ProcessTextFromPointerToID",
                   "PlaceTextItems", "PrintText", "PrintTextNoDelay",
                   "DrawTextReadyLabeledOrRegularTextBox"),
    "frames": ("DoAFrames", "DoFrame", "HandleDPadRepeat"),
    "lcd": ("EnableLCD", "DisableLCD", "Set_OBJ_8x8", "Set_OBJ_8x16", "SetWindowOn",
            "SetWindowOff"),
    "card_collection": ("CreateTempCardCollection", "AddCardToCollection",
                        "GetCardAlbumProgress"),
    "save": ("CopyGeneralSaveDataToSRAM", "ValidateGeneralSaveDataFromDE",
             "LoadGeneralSaveDataFromDE", "WriteDataToBackup", "LoadDataFromBackup",
             "WriteBackupGeneralSaveData", "WriteBackupCardAndDeckSaveData",
             "LoadBackupGeneralSaveData", "LoadBackupCardAndDeckSaveData",
             "InvalidateSaveData", "UpdateAlbumProgress", "LoadAlbumProgressFromSRAM",
             "LoadBackupSaveData", "_LoadGeneralSaveData",
             "_AddCardToCollectionAndUpdateAlbumProgress",
             "ValidateBackupGeneralSaveData", "_ValidateGeneralSaveData",
             "SaveGeneralSaveDataFromDE", "_SaveGeneralSaveData",
             "SaveAndBackupData", "_SaveGame"),
    "dma": ("DMA",),
    "unsafe_bg_map": ("UnsafeWriteDataBlockToBGMap0",),
    "sram": ("BankswitchSRAM",),
    "lcd_enable_frame": ("DoFrameIfLCDEnabled",),
    "palettes": ("FlushAllPalettes", "FlushPalette", "SetBGP", "FlushPalette0",
                  "FlushPalettes", "SetOBP0", "SetOBP1", "FlushPalettesIfRequested"),
    "scroll": ("Func_3e44", "GetNextBackgroundScroll", "EnableInt_LYCoincidence",
                "DisableInt_LYCoincidence"),
    "damage": ("AddToDamage",),
    "objects": ("SetOneObjectAttributes", "ZeroObjectPositions"),
    "time": ("IncrementPlayTimeCounter", "CheckForCGB"),
    "coin_toss": ("CompareDEtoBC",),
    "clear_sram": ("ClearSRAMBank", "RestartSRAM"),
    "card_data": ("GetCardType", "GetCardName", "GetCardTypeRarityAndSet",
                  "LoadCardDataToBuffer1_FromCardID", "LoadCardDataToBuffer2_FromCardID",
                  "LoadCardDataToBuffer1_FromName", "LoadCardGfx"),
    "load_deck": ("LoadDeck",),
    "card_color": ("GetCardWeakness", "GetArenaCardWeakness", "GetPlayAreaCardWeakness",
                   "GetCardResistance", "GetArenaCardResistance", "GetPlayAreaCardResistance"),
}

ALL = tuple(fn for group in ROUTINES.values() for fn in group)
