#!/usr/bin/env python3
"""poketcg.sym -> C layout headers.

rgblink emits one symbol per line as ``BB:AAAA Label`` (BB = 2-digit hex bank,
AAAA = 4-digit lowercase hex address).  For every bank-0 symbol landing in a RAM
region we emit three macros, because the .sym carries no size information and a
guess either way would be wrong for half the symbols:

    #define wRNG1_ADDR 0xCACAu
    #define wRNG1      (*(uint8_t *)(g_wram + (0xCACAu - 0xC000u)))
    #define wRNG1_PTR  ((uint8_t  *)(g_wram + (0xCACAu - 0xC000u)))

sram additionally accepts banks 1-3 (the cart has 4 SRAM banks). A banked
symbol has no valid flat lvalue under the single-window ``g_sram`` array, so
it gets only two macros instead of three:

    #define sBackupGeneralSaveData_ADDR 0xB800u
    #define sBackupGeneralSaveData_BANK 2u
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SYM_RE = re.compile(r"^([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)\s*$")
# Trailing block of the .sym: bare `<hex> Label` text IDs, not addresses.
TEXTID_RE = re.compile(r"^[0-9A-Fa-f]{1,4}\s+\S+\s*$")

# region, base, end (inclusive), backing array, array size, max bank
REGIONS = [
    ("wram", 0xC000, 0xDFFF, "g_wram", 0x2000, 0),
    ("hram", 0xFF80, 0xFFFE, "g_hram", 0x80, 0),
    ("sram", 0xA000, 0xBFFF, "g_sram", 0x8000, 3),
]

HEADER = """\
/* Generated by tools/gen_layout.py from {sym}. Do not edit. */
#ifndef POKETCG_GENERATED_{GUARD}_H
#define POKETCG_GENERATED_{GUARD}_H

#include <assert.h>
#include <stdint.h>

#include "mem.h"

"""

FOOTER = """
static_assert({high}u - {base}u < {size}u,
              "{region} layout overflows {array}");

#endif /* POKETCG_GENERATED_{GUARD}_H */
"""


def parse(sym_path: Path) -> list[tuple[int, int, str]]:
    out = []
    for lineno, line in enumerate(sym_path.read_text().splitlines(), 1):
        line = line.strip()
        if not line or line.startswith(";"):
            continue
        m = SYM_RE.match(line)
        if not m:
            if not TEXTID_RE.match(line):
                print(f"{sym_path}:{lineno}: unparsable symbol line: {line!r}", file=sys.stderr)
            continue
        bank, addr, name = int(m[1], 16), int(m[2], 16), m[3]
        if "." in name:  # local label
            continue
        out.append((bank, addr, name))
    return out


def emit(region: str, base: int, end: int, array: str, size: int, max_bank: int,
         syms: list[tuple[int, int, str]], sym_path: Path, out_dir: Path) -> int:
    seen: dict[str, tuple[int, int]] = {}
    rows: list[tuple[int, str, int]] = []
    for bank, addr, name in syms:
        if not (0 <= bank <= max_bank) or not (base <= addr <= end):
            continue
        if name in seen:
            if seen[name] != (bank, addr):
                prev_bank, prev_addr = seen[name]
                raise SystemExit(
                    f"symbol {name} appears at both {prev_bank:02d}:${prev_addr:04X} "
                    f"and {bank:02d}:${addr:04X}")
            continue
        seen[name] = (bank, addr)
        rows.append((bank, name, addr))

    rows.sort(key=lambda r: (r[0], r[2], r[1]))
    high = max((a for bank, _, a in rows if bank == 0), default=base)

    guard = region.upper()
    body = [HEADER.format(sym=sym_path.name, GUARD=guard)]
    width = max((len(n) for _, n, _ in rows), default=1)
    for bank, name, addr in rows:
        if bank == 0:
            off = f"(0x{addr:04X}u - 0x{base:04X}u)"
            body.append(f"#define {name + '_ADDR':<{width + 5}} 0x{addr:04X}u\n")
            body.append(f"#define {name:<{width + 5}} (*(uint8_t *)({array} + {off}))\n")
            body.append(f"#define {name + '_PTR':<{width + 5}} ((uint8_t *)({array} + {off}))\n")
        else:
            body.append(f"#define {name + '_ADDR':<{width + 5}} 0x{addr:04X}u\n")
            body.append(f"#define {name + '_BANK':<{width + 5}} {bank}u\n")
    body.append(FOOTER.format(high=f"0x{high:04X}", base=f"0x{base:04X}", size=f"0x{size:X}",
                              region=region, array=array, GUARD=guard))

    dest = out_dir / f"{region}.h"
    text = "".join(body)
    if not dest.exists() or dest.read_text() != text:
        dest.write_text(text)
    return len(rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sym", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    args = ap.parse_args()

    if not args.sym.exists():
        raise SystemExit(f"symbol file not found: {args.sym} (run `just bootstrap`)")
    args.out.mkdir(parents=True, exist_ok=True)

    syms = parse(args.sym)
    for region, base, end, array, size, max_bank in REGIONS:
        n = emit(region, base, end, array, size, max_bank, syms, args.sym, args.out)
        print(f"gen_layout: {region}.h  {n} symbols")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
