#!/usr/bin/env python3
"""Generate the required-bank table for every ported `farcall` target.

`farcall` selects the callee's bank and restores the caller's on return
(poketcg/src/home/farcall.asm). The port calls the C function directly, so the
switch has to come from somewhere; giving it to the callee on entry closes the
whole class at once instead of auditing 988 call sites. Only targets in banked
space need an entry: the home region below $4000 is always mapped.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

FAR_CALL = re.compile(r"^\s+(?:farcall|bank1call|callfar)\s+([A-Za-z_][\w.]*)")
SYM_LINE = re.compile(r"^([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)\s*$")
DECL = re.compile(r"^[A-Za-z_][\w \*]*?\b(\w+)\s*\(", re.MULTILINE)


def far_call_targets(asm_root: Path) -> set[str]:
    targets: set[str] = set()
    for path in sorted(asm_root.rglob("*.asm")):
        for line in path.read_text(errors="replace").splitlines():
            match = FAR_CALL.match(line)
            if match and "." not in match.group(1):
                targets.add(match.group(1))
    return targets


def symbol_table(sym_path: Path) -> dict[str, tuple[int, int]]:
    table: dict[str, tuple[int, int]] = {}
    for line in sym_path.read_text().splitlines():
        match = SYM_LINE.match(line)
        if match:
            table.setdefault(
                match.group(3), (int(match.group(1), 16), int(match.group(2), 16))
            )
    return table


def declared_in(home: Path) -> dict[str, str]:
    owners: dict[str, str] = {}
    for header in sorted(home.glob("*.h")):
        for name in DECL.findall(header.read_text(errors="replace")):
            owners.setdefault(name, header.name)
    return owners


def render(sym_path: Path, asm_root: Path, home: Path) -> str:
    table = symbol_table(sym_path)
    owners = declared_in(home)

    unresolved = sorted(n for n in far_call_targets(asm_root) if n not in table)
    if unresolved:
        raise SystemExit(f"farcall targets missing from poketcg.sym: {unresolved}")

    rows: dict[str, int] = {}
    for name in sorted(far_call_targets(asm_root)):
        bank, offset = table[name]
        if offset < 0x4000 or name not in owners:
            continue
        rows[name] = bank

    headers = sorted({owners[name] for name in rows})
    include_lines = "\n".join(f'#include "home/{header}"' for header in headers)
    entries = "\n".join(
        f"\t{{ (const void *)&{name}, 0x{bank:02X}u }},"
        for name, bank in sorted(rows.items())
    )
    return f'''/* Generated by tools/gen_bank_guard.py. Do not edit. */
#include "bank_guard.h"

{include_lines}

const BankGuardEntry kBankGuardEntries[] = {{
{entries}
}};

const size_t kBankGuardCount =
\tsizeof(kBankGuardEntries) / sizeof(kBankGuardEntries[0]);
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sym", type=Path, required=True)
    parser.add_argument("--asm-root", type=Path, required=True)
    parser.add_argument("--home", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = render(args.sym, args.asm_root, args.home)
    if not args.output.is_file() or args.output.read_text() != content:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
