#!/usr/bin/env python3
"""Generate the script entry address table from poketcg.sym plus the ROM.

Two sites reach a script by a computed jump, and both need the target resolved
ahead of time because deciding at run time would mean reading ROM code as data,
which the product data pack does not carry.

EnterScript (engine/overworld/overworld.asm:122-127) ends in `jp hl` with hl
taken from wNextScript. Every `Script_*` label that opens with the
`start_script` macro is a lone `rst $20` and is interpreted by RST20; the rest
are ordinary routines needing a C body.

CallMapScriptPointerIfExists (engine/overworld/scripting.asm:98-101) ends in
`jp hl` with hl read out of the MapScripts table, whose targets are named in
data/map_scripts.asm and are all ordinary routines.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

OPCODE_RST_20 = 0xE7
SYM_LINE = re.compile(r"^([0-9A-Fa-f]{2}):([0-9A-Fa-f]{4})\s+(\S+)\s*$")
DECL = re.compile(r"^[A-Za-z_][\w ]*\**\s*\b(\w+)\s*\(\s*void\s*\)\s*;", re.MULTILINE)
MAP_SCRIPT_TARGET = re.compile(r"^\tdw\s+(\w+)\s*$", re.MULTILINE)


def symbol_table(sym_path: Path) -> dict[str, tuple[int, int]]:
    table: dict[str, tuple[int, int]] = {}
    for line in sym_path.read_text().splitlines():
        match = SYM_LINE.match(line)
        if match:
            table.setdefault(
                match.group(3), (int(match.group(1), 16), int(match.group(2), 16))
            )
    return table


def script_entries(sym_path: Path, rom_path: Path, map_scripts: Path
                   ) -> dict[int, tuple[int, int, list[str]]]:
    rom = rom_path.read_bytes()
    table = symbol_table(sym_path)
    wanted = {
        name for name in table
        if name.startswith("Script_") and "." not in name
    }
    wanted |= {
        name for name in MAP_SCRIPT_TARGET.findall(map_scripts.read_text())
        if name != "NULL"
    }
    unresolved = sorted(name for name in wanted if name not in table)
    if unresolved:
        raise SystemExit(f"script entry targets missing from poketcg.sym: {unresolved}")

    found: dict[int, tuple[int, int, list[str]]] = {}
    for name in sorted(wanted):
        bank, offset = table[name]
        physical = bank * 0x4000 + (offset - 0x4000 if offset >= 0x4000 else offset)
        if physical >= len(rom):
            raise SystemExit(f"{name} at {bank:02X}:{offset:04X} is past the ROM")
        entry = found.setdefault(offset, (bank, rom[physical], []))
        if entry[0] != bank:
            raise SystemExit(
                f"${offset:04X} is claimed by bank {entry[0]:02X} and {bank:02X}; "
                "the table keys on the 16-bit address a `jp hl` carries"
            )
        entry[2].append(name)
    return found


def ported_symbols(home: Path) -> dict[str, str]:
    owners: dict[str, str] = {}
    for header in sorted(home.glob("*.h")):
        for name in DECL.findall(header.read_text()):
            owners.setdefault(name, header.name)
    return owners


def render(sym_path: Path, rom_path: Path, home: Path, map_scripts: Path) -> str:
    entries = script_entries(sym_path, rom_path, map_scripts)
    owners = ported_symbols(home)

    rows, thunks = [], []
    headers = {"scripting.h"}
    for offset in sorted(entries):
        _bank, opcode, names = entries[offset]
        ported = sorted(name for name in names if name in owners)
        name = ported[0] if ported else sorted(names)[0]
        if opcode == OPCODE_RST_20:
            rows.append(f'\t{{ 0x{offset:04X}u, "{name}", SCRIPT_ENTRY_BYTECODE, NULL }},')
        elif ported:
            headers.add(owners[name])
            thunks.append(f"static void enter_{name}(void)\n{{\n\t(void){name}();\n}}\n")
            rows.append(f'\t{{ 0x{offset:04X}u, "{name}", SCRIPT_ENTRY_ROUTINE, enter_{name} }},')
        else:
            rows.append(f'\t{{ 0x{offset:04X}u, "{name}", SCRIPT_ENTRY_UNPORTED, NULL }},')

    include_lines = "\n".join(f'#include "home/{header}"' for header in sorted(headers))
    body = "\n".join(thunks)
    table = "\n".join(rows)
    return f'''/* Generated by tools/gen_script_entry_dispatch.py. Do not edit. */
#include "home/script_entry_dispatch.h"

#include <stdio.h>
#include <stdlib.h>

#include "mem.h"

{include_lines}

{body}
static const ScriptEntryRow kScriptEntries[] = {{
{table}
}};

#define SCRIPT_ENTRY_COUNT \\
\t((uint16_t)(sizeof(kScriptEntries) / sizeof(kScriptEntries[0])))

const ScriptEntryRow *ScriptEntryLookup(uint16_t address)
{{
\tuint16_t low = 0u;
\tuint16_t high = SCRIPT_ENTRY_COUNT;

\twhile (low < high) {{
\t\tuint16_t middle = (uint16_t)(low + (uint16_t)((high - low) / 2u));

\t\tif (kScriptEntries[middle].address < address)
\t\t\tlow = (uint16_t)(middle + 1u);
\t\telse
\t\t\thigh = middle;
\t}}
\tif (low < SCRIPT_ENTRY_COUNT && kScriptEntries[low].address == address)
\t\treturn &kScriptEntries[low];
\treturn NULL;
}}

void ScriptEntryEnter(uint16_t target)
{{
\tconst ScriptEntryRow *row;

\t/* Every shipped script entry is in ROM bank $03, so a RAM target only
\t * happens under a probe case that stubs the jump destination. RAM is
\t * readable through the bus, unlike ROM code, so decode the stub: `ret`
\t * ($C9) returns to EnterScript's caller and `rst $20` ($E7) enters the
\t * interpreter, exactly as the CPU would. */
\tif (target >= 0xC000u) {{
\t\tuint8_t opcode = gb_read8(target);

\t\tif (opcode == 0xC9u)
\t\t\treturn;
\t\tif (opcode == 0xE7u) {{
\t\t\t(void)RST20(0u, 0u, 0u, 0u, 0u, 0u, (uint16_t)(target + 1u));
\t\t\treturn;
\t\t}}
\t\tfprintf(stderr, "script entry ram opcode=$%02X target=$%04X\\n",
\t\t        (unsigned)opcode, (unsigned)target);
\t\tabort();
\t}}
\trow = ScriptEntryLookup(target);
\tif (row == NULL) {{
\t\tfprintf(stderr, "script entry miss target=$%04X\\n", (unsigned)target);
\t\tabort();
\t}}
\tswitch (row->kind) {{
\tcase SCRIPT_ENTRY_BYTECODE:
\t\t(void)RST20(0u, 0u, 0u, 0u, 0u, 0u, (uint16_t)(target + 1u));
\t\treturn;
\tcase SCRIPT_ENTRY_ROUTINE:
\t\trow->function();
\t\treturn;
\tdefault:
\t\tfprintf(stderr, "script entry unported name=%s target=$%04X\\n",
\t\t        row->name, (unsigned)target);
\t\tabort();
\t}}
}}
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sym", type=Path, required=True)
    parser.add_argument("--rom", type=Path, required=True)
    parser.add_argument("--home", type=Path, required=True)
    parser.add_argument("--map-scripts", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    content = render(args.sym, args.rom, args.home, args.map_scripts)
    if not args.output.is_file() or args.output.read_text() != content:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
