#include "probe.h"

#include <string.h>

/* probe_groups.h is generated by CMake from the src/probe glob and holds one
 * PROBE_GROUP(<basename>) line per adapter translation unit. */
#define PROBE_GROUP(n) extern const ProbeEntry probe_entries_##n[];
#include "probe_groups.h"
#undef PROBE_GROUP

static const ProbeEntry *const k_groups[] = {
#define PROBE_GROUP(n) probe_entries_##n,
#include "probe_groups.h"
#undef PROBE_GROUP
	NULL
};

ProbeFn probe_lookup(const char *name)
{
	for (const ProbeEntry *const *g = k_groups; *g; g++)
		for (const ProbeEntry *e = *g; e->name; e++)
			if (strcmp(e->name, name) == 0)
				return e->fn;
	return NULL;
}
